
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AUT_USERS_MONTHLY_COUNT" ("MONTH_YEAR", "NEW_USERS") AS 
  SELECT 
    TO_CHAR(USR_CREATED_DATE, 'FMMonth YYYY') AS MONTH_YEAR, 
    COUNT(*) AS NEW_USERS
  FROM AUT_USERS
  GROUP BY 
    TO_CHAR(USR_CREATED_DATE, 'FMMonth YYYY'), 
    EXTRACT(YEAR FROM USR_CREATED_DATE), 
    EXTRACT(MONTH FROM USR_CREATED_DATE)
  ORDER BY 
    EXTRACT(YEAR FROM USR_CREATED_DATE) ASC, 
    EXTRACT(MONTH FROM USR_CREATED_DATE) ASC;