
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "KLANTEN_VIEW" ("USR_ID", "USR_USERNAME", "USR_PASSWORD", "USR_EMAIL", "USR_CREATED_DATE", "USR_CREATED_BY", "USR_MODIFIED_DATE", "USR_MODIFIED_BY", "USR_DELETED") AS 
  SELECT 
  AUT_USERS.USR_ID, 
  AUT_USERS.USR_USERNAME, 
  AUT_USERS.USR_EMAIL, 
  AUT_USERS.USR_PASSWORD, 
  AUT_USERS.USR_CREATED_DATE,
  AUT_USERS.USR_CREATED_BY,
  AUT_USERS.USR_MODIFIED_DATE,
  AUT_USERS.USR_MODIFIED_BY,
  AUT_USERS.USR_DELETED        
FROM 
  AUT_USERS
JOIN 
  AUT_USR_RLE ON AUT_USERS.USR_ID = AUT_USR_RLE.URE_USR_ID
JOIN 
  AUT_ROLES ON AUT_USR_RLE.URE_RLE_ID = AUT_ROLES.RLE_ID
WHERE 
  UPPER(AUT_ROLES.RLE_NAME) = 'KLANT';