
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "USER_ROLE_VIEW" ("USR_ID", "USR_USERNAME", "USR_EMAIL", "RLE_NAME", "RLE_DESCRIPTION") AS 
  SELECT 
    u.USR_ID,
    u.USR_USERNAME,
    u.USR_EMAIL,
    r.RLE_NAME,
    r.RLE_DESCRIPTION
FROM 
    AUT_USERS u
JOIN 
    AUT_USR_RLE ur ON u.USR_ID = ur.URE_USR_ID
JOIN 
    AUT_ROLES r ON ur.URE_RLE_ID = r.RLE_ID;